version: "3"
services:
  practice:
    image: postgres:latest
    restart: always
    container_name: sql_practice
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=sql_practice
      - DATABASE_HOST=localhost
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "practice.data:/var/lib/postgresql/data"

volumes:
  practice.data: